name: "LLM Council Tool (MVP)"
description: "Reviews GitHub pull requests using an LLM and posts feedback."
author: "Kimeo + Clawd"

inputs:
  openai_api_key:
    description: "OpenAI API key"
    required: true
  openai_model:
    description: "Model name"
    required: false
    default: "gpt-4.1-mini"
  max_files:
    description: "Max files to review"
    required: false
    default: "25"
  max_patch_chars:
    description: "Max characters of patch to send per file"
    required: false
    default: "6000"

runs:
  using: "node20"
  main: "dist/index.js"
